# GET http://localhost:8000/api/users

# GET http://localhost:8000/api/users/getUser/65dc7d7aa907c9d7e946608f

###

# POST http://localhost:8000/api/users/createUser
# Content-Type: application/json

# [
#   {
#   "name": "Yennego Yennego",
#   "email": "yenne@gmail.com",
#   "password": "111111",
#   "roles": "admin"
#   },

#   {
#   "name": "Kun Kollie",
#   "email": "kjun@gmail.com",
#   "password": "999999",
#   "roles": "student"
#   }
# ]

# POST http://localhost:8000/api/users/createUsersBatch
# Content-Type: application/json

# [
#   {
#   "name": "Peter Paul",
#   "email": "ppaul@gmail.com",
#   "password": "777777",
#   "roles": "student"
#   },

#   {
#   "name": "Young Old",
#   "email": "ygold@gmail.com",
#   "password": "12345678",
#   "roles": "student"
#   }
# ]

###

PUT http://localhost:8000/api/users/updateUser/65dc7d7aa907c9d7e946608f
Content-Type: application/json

{
  "name": "Zayzay Yen",
  "email": "yen@gmail.com",
  "password": "123zayzay",
  "roles": "admin"
}

# DELETE http://localhost:8000/api/users/deleteUser/65dca2116188d9363e7d6e26
